"""`bench-vision setup`: discover cameras, print a pasteable report, write a starter config.toml."""

from __future__ import annotations

import os
import platform
import sys
import tomllib
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path
from typing import TextIO

from .config import BY_ID_PREFIX, parse_config
from .errors import BenchVisionError
from .v4l2 import V4L2, ControlInfo, PixelFormat, parse_formats, parse_list_ctrls

# Preferred capture formats, best first (MJPG keeps 4K within USB 2 bandwidth).
FOURCC_PREFERENCE = ("MJPG", "YUYV")
UNDECODABLE = {"H264", "HEVC", "H265"}  # OpenCV's V4L2 backend can't decode these
# The TOMLOV microscope reports itself as "RaySmartTech VMS700B" over USB.
NAME_HINTS = (("arducam", "side"), ("tomlov", "scope"), ("microscope", "scope"), ("vms700", "scope"))


@dataclass
class Device:
    by_id: str
    target: str
    formats: list[PixelFormat]
    controls_raw: str
    controls: dict[str, ControlInfo]
    error: str | None = None


def list_by_id(by_id_dir: Path) -> list[tuple[str, str]]:
    """(by-id path, resolved /dev/videoN) for every entry, sorted."""
    try:
        entries = sorted(by_id_dir.iterdir())
    except FileNotFoundError:
        return []
    except OSError as e:
        raise BenchVisionError(f"Could not list {by_id_dir}: {e.strerror or e}.") from None
    out = []
    for p in entries:
        try:
            target = os.path.realpath(p)
        except OSError:
            target = "?"
        out.append((str(p), target))
    return out


def best_mode(formats: list[PixelFormat]) -> tuple[str, tuple[int, int]] | None:
    """Largest resolution in the most preferred format that has one."""
    by_cc = {f.fourcc: f for f in formats if f.sizes and f.fourcc not in UNDECODABLE}
    for cc in FOURCC_PREFERENCE + tuple(by_cc):
        f = by_cc.get(cc)
        if f:
            return cc, max(f.sizes, key=lambda s: s[0] * s[1])
    return None


def guess_name(by_id: str, taken: set[str]) -> str:
    low = Path(by_id).name.lower()
    for hint, name in NAME_HINTS:
        if hint in low and name not in taken:
            return name
    n = 1
    while f"cam{n}" in taken:
        n += 1
    return f"cam{n}"


def probe(v4l2: V4L2, by_id: str, target: str) -> Device:
    try:
        formats = parse_formats(v4l2.list_formats(by_id))
        raw = v4l2.list_ctrls_menus(by_id)
        return Device(by_id, target, formats, raw, parse_list_ctrls(raw))
    except BenchVisionError as e:
        return Device(by_id, target, [], "", {}, error=str(e))


def starter_config(devices: list[Device]) -> str:
    lines = [
        "# Generated by `bench-vision setup`. Check the camera names, then restart the MCP server.",
        "# Device paths are stable /dev/v4l/by-id/ links; never use bare /dev/videoN.",
        "",
        "[server]",
        "jpeg_quality = 85",
    ]
    taken: set[str] = set()
    for d in devices:
        mode = best_mode(d.formats)
        if mode is None:
            continue
        cc, (w, h) = mode
        name = guess_name(d.by_id, taken)
        taken.add(name)
        controls = []
        focus = d.controls.get("focus_absolute")
        # newer kernels: focus_automatic_continuous; older ones: focus_auto
        auto = next((n for n in ("focus_automatic_continuous", "focus_auto") if n in d.controls), None)
        settable = focus is not None and not focus.read_only and focus.min != focus.max
        if auto and settable and not d.controls[auto].read_only:
            # Autofocus hunts while you solder: lock it at the current position.
            controls = [f"{auto}=0", f"focus_absolute={focus.value or 0}"]
        rendered = ", ".join(f'"{c}"' for c in controls)
        lines += [
            "",
            f"[cameras.{name}]",
            f'device = "{BY_ID_PREFIX}{Path(d.by_id).name}"',
            f"resolution = [{w}, {h}]",
            f'fourcc = "{cc}"',
            "default_rotation = 0",
            f"v4l2_controls = [{rendered}]",
        ]
    return "\n".join(lines) + "\n"


def _fmt_rates(rates: list[float]) -> str:
    return "/".join(f"{r:g}" for r in sorted(set(rates), reverse=True)) + " fps" if rates else ""


def run_setup(
    root: Path,
    force: bool = False,
    v4l2: V4L2 | None = None,
    by_id_dir: Path = Path(BY_ID_PREFIX),
    out: TextIO = sys.stdout,
) -> int:
    """Print the report to `out` and write a starter config. Returns the exit code."""
    v4l2 = v4l2 or V4L2()
    v4l2.require()  # one-line "needs Linux/v4l2" on a Mac

    def p(line: str = "") -> None:
        print(line, file=out)

    try:
        version = metadata.version("bench-vision")
    except metadata.PackageNotFoundError:
        version = "unknown"
    p("===== bench-vision setup report (paste everything between the ===== lines) =====")
    p(f"bench-vision {version} | {platform.platform()} | Python {platform.python_version()} | {v4l2.version()}")
    p()
    p("--- v4l2-ctl --list-devices ---")
    p(v4l2.list_devices().rstrip() or "(no devices)")
    p()
    entries = list_by_id(by_id_dir)
    p(f"--- {by_id_dir} ---")
    if not entries:
        p("(empty: no USB cameras with stable by-id names are plugged in)")
    for path, target in entries:
        p(f"{path} -> {target}")

    devices = [probe(v4l2, path, target) for path, target in entries]
    for d in devices:
        p()
        p(f"=== {d.by_id} ({d.target}) ===")
        if d.error:
            p(f"error: {d.error}")
            continue
        capture = [f for f in d.formats if f.sizes]
        if not capture:
            p("no capture formats (probably a metadata node; ignored)")
            continue
        p("formats:")
        for f in capture:
            p(f"  {f.fourcc} ({f.description})")
            for (w, h), rates in sorted(f.sizes.items(), key=lambda kv: -kv[0][0] * kv[0][1]):
                p(f"    {w}x{h}  {_fmt_rates(rates)}".rstrip())
        p("controls:")
        p("\n".join("  " + line.strip() for line in d.controls_raw.splitlines() if line.strip()) or "  (none)")

    config_text = starter_config(devices)
    cams = [d for d in devices if best_mode(d.formats)]
    p()
    p("--- starter config ---")
    if not cams:
        p("No capture devices found, so no config was written. Plug the cameras in and run setup again.")
        p("===== end of report =====")
        return 1
    parse_config(tomllib.loads(config_text), where="generated config")  # must load cleanly
    target = root / "config.toml"
    if target.exists() and not force:
        target = root / "config.generated.toml"
        note = "config.toml already exists, so this was written to config.generated.toml (use --force to overwrite)"
    else:
        note = f"written to {target.name}"
    try:
        target.write_text(config_text, encoding="utf-8")
    except OSError as e:
        raise BenchVisionError(f"Could not write {target}: {e.strerror or e}.") from None
    p(f"({note})")
    p(config_text.rstrip())
    p("===== end of report =====")
    return 0
